[tools]
bun = "1.3.3"
deno = "2.3.3"
go = "latest"
neovim = ['0.11.4']
node = ['23.11.0']
pkl = "0.28.2"
python = "latest"
uv = "latest"
rust = "latest"
"npm:@openai/codex" = "latest"
"npm:vercel" = "latest"
"npm:@terragon-labs/cli" = "latest"
"npm:opencode-ai" = "1.0.191"
claude-code = "2.1.6"
"npm:@sourcegraph/amp" = "0.0.1768035453-g894cb5"
"npm:@beads/bd" = "0.29.0"
"npm:agent-browser" = "latest"
"npm:@mariozechner/gccli" = "latest"
"npm:@mariozechner/gmcli" = "latest"
"npm:@mariozechner/pi-coding-agent" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
experimental = true

# Mise on NixOS sets this to true by default https://mise.jdx.dev/configuration/settings.html#all_compile
# We have programs.nix-ld.enable = true; so we don't need to compile everything
all_compile = false
